version: '3.12'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4t5y
      - POSTGRES_HOST=172.18.0.2
    restart: always
    ports:
      - "5432:5432"
  web:
    container_name: stocks
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4t5y
      - POSTGRES_HOST=172.18.0.2
    restart: unless-stopped
    entrypoint : ["bash", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]