version: '3.12'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4t5y
      - POSTGRES_HOST=172.18.0.2
    restart: always
    ports:
      - "5432:5432"
  nginx:
      image: nginx:stable
      restart: always
      ports:
        - "8080:80"
      environment:
        - DJANGO_HOST=web
      volumes:
        - ./default.conf.template:/etc/nginx/templates/default.conf.template
        - ./www:/www
  web:
    container_name: stocks
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3r4t5y
      - POSTGRES_HOST=172.18.0.2
    restart: unless-stopped
    volumes:
      - .:/app
      - ./www:/www
    entrypoint: ["bash", "-c", "python manage.py migrate 
    && python manage.py runserver 0.0.0.0:8000 
    && manage.py collectstatic --noinput"]
